VAGRANTFILE_API_VERSION = "2"

# Require YAML module
require 'yaml'

# Read YAML file with box details
servers = YAML.load_file('servers.yaml')

# Create boxes
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

if index == servers.size - 1  
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "contrail-ansible-deployer/playbooks/configure_instances.yml"
    ansible.inventory_path = "contrail-ansible-deployer/inventory"
    ansible.verbose = true
  end

if Vagrant.has_plugin?("vagrant-timezone")
     config.timezone.value="America/New_York"
  end

  # Iterate through entries in YAML file
  servers.each do |servers|
    config.vm.define servers["name"] do |srv|
      srv.vm.box = servers["box"]
      srv.vm.network "public_network", bridge: "br0", ip: servers["ip-mgmt"]
      srv.vm.network "public_network", bridge: "br1", ip: servers["ip-control-data"]
      srv.vm.provision "shell", path: "../scripts/enable_root_login.sh"
      srv.vm.provision "shell", path: "../scripts/set-centos-gw.sh"
      srv.vm.provision "shell", path: "../scripts/ntp.sh" 
      srv.vm.provision "file", source: "instances.yaml", destination: "/home/vagrant/instances.yaml"
#      srv.vm.provision "shell", path: "../scripts/mn-ansible-k8s.sh"
      srv.vm.hostname = servers ["name"]
      srv.vm.provider :virtualbox do |vb|
        vb.name = servers["name"]
        vb.memory = servers["ram"]
        if servers.has_key?("cpus")
          vb.cpus = servers["cpus"]
          vb.customize ["setextradata", :id, "VBoxInternal/CPUM/SSE4.1", "1"]
          vb.customize ["setextradata", :id, "VBoxInternal/CPUM/SSE4.2", "1"]
          vb.customize ["modifyvm", :id, "--paravirtprovider", "kvm"]
          end
        end
      end
  end
end
